/**
 * Explore screen layout constants.
 */

/** Expanded custom iOS header height below the safe area. */
export const IOS_EXPLORE_HEADER_BODY_HEIGHT = 176;

/** Extra header height for each Dynamic Type scale step above the default. */
export const IOS_EXPLORE_HEADER_FONT_SCALE_ALLOWANCE = 72;

export {
  COLLAPSING_HEADER_BLUR_INTENSITY as IOS_EXPLORE_HEADER_BLUR_INTENSITY,
  COLLAPSING_HEADER_DISTANCE as IOS_EXPLORE_HEADER_COLLAPSE_DISTANCE,
  COLLAPSING_HEADER_TRANSLATION as IOS_EXPLORE_HEADER_TRANSLATION,
} from "@/components/collapsing-screen-header/constants";

export {
  ACTIVITY_CARD_BODY_HEIGHT as EXPLORE_CARD_BODY_HEIGHT,
  ACTIVITY_CARD_CAROUSEL_MAX_FONT_SCALE as EXPLORE_CARD_CAROUSEL_MAX_FONT_SCALE,
  ACTIVITY_CARD_GAP as EXPLORE_CARD_GAP,
  ACTIVITY_CARD_HAPTIC_AMPLITUDE as EXPLORE_CARD_HAPTIC_AMPLITUDE,
  ACTIVITY_CARD_HAPTIC_FREQUENCY as EXPLORE_CARD_HAPTIC_FREQUENCY,
  ACTIVITY_CARD_INACTIVE_BLUR_OPACITY as EXPLORE_CARD_INACTIVE_BLUR_OPACITY,
  ACTIVITY_CARD_INACTIVE_BLUR_RADIUS as EXPLORE_CARD_INACTIVE_BLUR_RADIUS,
  ACTIVITY_CARD_INACTIVE_OPACITY as EXPLORE_CARD_INACTIVE_OPACITY,
  ACTIVITY_CARD_INACTIVE_SCALE as EXPLORE_CARD_INACTIVE_SCALE,
  ACTIVITY_CARD_MEDIA_ASPECT_RATIO as EXPLORE_CARD_MEDIA_ASPECT_RATIO,
  ACTIVITY_CARD_MEDIA_MAX_HEIGHT as EXPLORE_CARD_MEDIA_MAX_HEIGHT,
  ACTIVITY_CARD_TOP_SPACING as EXPLORE_CARD_TOP_SPACING,
} from "@/components/activity-card-carousel/constants";
